window.sceneConfig = {
  version: 1,
  image: {
    src: "./assets/office-scene-clean.png",
    width: 1024,
    height: 576,
  },
  grid: {
    width: 18,
    height: 13,
    origin: {
      x: 500,
      y: 120,
      anchor: "center of grid cell (0,0)",
    },
    tileWidth: 64,
    tileHeight: 32,
    tileDepth: 12,
    coordinateSystem: "gridX moves down-right, gridY moves down-left",
    estimateConfidence: "medium",
  },
  playerStart: {
    x: 9,
    y: 10,
  },
  movement: {
    moveSpeed: 0.16,
    cellsPerSecond: 3.4,
  },
  character: {
    sprite: {
      src: "./assets/character-spritesheet-normalized.png",
      columns: 3,
      rows: 4,
      renderWidth: 142,
      renderHeight: 170,
      anchorX: 0.5,
      anchorY: 1,
      footOffsetY: 12,
      idleFrame: 1,
      walkFrames: [0, 1, 2, 1],
      animationFps: 7,
      directionRows: {
        down: 0,
        up: 1,
        left: 2,
        right: 3,
      },
    },
  },
  debug: {
    showGrid: false,
    showCollision: false,
  },
  obstacles: [
    {
      id: "kitchen-counter",
      label: "back kitchen counter and coffee bar",
      cells: [
        [1, 0],
        [1, 1],
        [2, 0],
        [2, 1],
        [3, 0],
        [3, 1],
        [4, 0],
        [4, 1],
        [5, 0],
        [5, 1],
        [6, 0],
        [6, 1],
        [7, 0],
        [7, 1],
        [8, 0],
        [8, 1],
        [9, 0],
        [9, 1],
      ],
    },
    {
      id: "left-floor-plant",
      label: "large potted plant",
      cells: [
        [0, 5],
        [1, 5],
      ],
    },
    {
      id: "water-dispenser",
      label: "water dispenser",
      cells: [
        [8, 0],
        [8, 1],
        [9, 0],
        [9, 1],
      ],
    },
    {
      id: "right-storage",
      label: "right window cabinet",
      cells: [
        [11, 1],
        [11, 2],
        [12, 1],
        [12, 2],
        [13, 1],
        [13, 2],
        [14, 1],
        [14, 2],
      ],
    },
    {
      id: "meeting-table-and-chairs",
      label: "meeting table and chairs",
      cells: [
        [9, 8],
        [10, 8],
        [12, 8],
        [13, 8],
        [10, 9],
        [11, 9],
        [12, 9],
        [13, 9],
        [14, 9],
        [10, 10],
        [11, 10],
        [12, 10],
        [13, 10],
        [14, 10],
        [10, 11],
        [11, 11],
        [12, 11],
        [13, 11],
        [14, 11],
        [11, 12],
        [12, 12],
        [13, 12],
      ],
    },
    {
      id: "trash-bin",
      label: "trash bin",
      cells: [
        [15, 0],
        [16, 0],
        [16, 1],
      ],
    },
  ],
  analysis: {
    gridEstimate:
      "The visible floor reads as about 18 columns by 13 rows. Treat this as a first-pass gameplay grid, not a pixel-perfect art trace.",
    originEstimate:
      "The logical (0,0) point is estimated at image pixel (500,120), near the back/top center of the isometric floor lattice.",
    tileEstimate:
      "Floor line spacing matches a standard 2:1 isometric tile, approximately 64px wide by 32px high.",
    notes:
      "Coordinates are approximate because furniture occludes many tile intersections. Tune origin by 4-8px after the final background image is added.",
  },
};
